### ISSUE TITLE
Pro tip Installation Issue

### ISSUE THREAD

**Issue by NikosSprocket** [moggieuk/ERCF-Software-V3#13]
I tried running the "Pro tip" installation for placing the new configuration files in the /tmp folder but I received the following error:

`Klipper service found
Linking ercf extension to Klipper...
ln: failed to create symbolic link '/tmp/klippy/extras/ercf.py': No such file or directory
`
Which is expected as klipper does not exist under /tmp.

Maybe, introduce a new option like "-t" (for test?) which will clone the klipper existing files under /tmp either with -k and -c custom location or without for the standard location under  `~/printer_data` per new MainsailOS 1.x and link per MainsailOS 0.9x.

**Comment by moggieuk** [comment]
Thanks I will address this in future update.  It is a harmless error but it should work nicely.   I'll look into the idea of a "test" install...

**Comment by NikosSprocket** [comment]
No worries! Low significance; just an FYI. Thanks!

**Comment by moggieuk** [comment]
I've made the fix in my local branch so it will roll up with upcoming v1.1.9 release. Thanks.

**Comment by moggieuk** [comment]
Closing because it is fixed.
