### ISSUE TITLE
extra_servo_dwell_up

### ISSUE THREAD

**Issue by RickDnamps** [moggieuk/ERCF-Software-V3#24]
Following Error

Option 'extra_servo_dwell_up' is not valid in section 'ercf'

Since I updated the new soft!! :(

**Comment by moggieuk** [comment]
This is expected and documented in the klipper error message (and in discord).  I have modified the installer to automatically remove these and that will make it in the next update.

**Comment by RickDnamps** [comment]
How I can fix that!! I can't run ERCF now! and I find nothing on Discord!
