### ISSUE TITLE
ercf_encoder needs to be named ercf_encoder in the config

### ISSUE THREAD

**Issue by cdiesch** [moggieuk/ERCF-Software-V3#28]
Setting the config requires the config section for `[ercf_encoder]` to be named `ercf_encoder` ie `[ercf_encoder encoder]` is not valid but `[ercf_encoder ercf_encoder]` is.

**Comment by moggieuk** [comment]
That is correct and as designed.  Is there an error in documentation somewhere?  I'm not sure exactly what "the fix" would be for this issue.

**Comment by moggieuk** [comment]
I'm going to close this issue but 'ercf_encoder' is as documented and it what is in the sample cfg file.
