### ISSUE TITLE
ERCF_EJECT: Take toolhead sensor into account

### ISSUE THREAD

**Issue by NyxCode** [moggieuk/ERCF-Software-V3#31]
Currently, when running ERCF_EJECT in an unknown state, the hotend heats up to extract the filament out of the nozzle.
Right now, this does not take the toolhead sensor into account. When the toolhead sensor does not see filament, the heating of the hotend should be skipped.

**Comment by moggieuk** [comment]
Ok, this is fixed now.  The "recover filament position" now uses the toolhead sensor exclusively to determine if filament is loaded.  Note that there is a corner case now that if the filament is past the extruder gears but not triggering the sensor, ERCF will incorrectly think the filament is unloaded.  This is way it did the heating/move test originally.  But on reflection I think the convenience and safety on not heating outweighs this case.
