### ISSUE TITLE
erreur syntax

### ISSUE THREAD

**Issue by Eloura74** [moggieuk/ERCF-Software-V3#37]
Warning: Error booting up ERCF: '>' not supported between instances of 'float' and 'NoneType'

why I have this syntax error, it is in ercf_software.cfg but why klipper can't read it?

**Comment by moggieuk** [comment]
This seems very specific to your system and not a syntax error but a type checking error.

Can you attach your ercf_software.cfg file?
Also, can you point to precisely what line is failing? 

It could be that one of your config variables in _ERCF_FROM_TIP_STANDALONE is of the wrong type.

**Comment by moggieuk** [comment]
I'm going to close this issue if I don't hear back because I do believe it is a specific problem with your environment.  No one else has reported it and it seems quite fundamental.
