### ISSUE TITLE
Internal error during connect: inconsistent use of tabs and spaces in indentation (ercf.py, line 1569)

### ISSUE THREAD

**Issue by MuddyPuddles4325** [moggieuk/ERCF-Software-V3#38]
![image](https://user-images.githubusercontent.com/13035594/227511802-936d9262-69e3-471a-8ac4-ad1162c46d51.png)
Looks like a tab accidentally got merged as well as a double "else" causing some syntax errors

**Comment by moggieuk** [comment]
Thank you.  I was busy going through PR's and this merge didn't go quite right. Fixed now.
