### ISSUE TITLE
Suppress manual filament actions while printer is printing (or endless spool is in affect)

### ISSUE THREAD

**Issue by nigelpjames** [moggieuk/ERCF-Software-V3#39]
I randomly hit eject (macro button) during a print and it unexpectedly ejected the filament. I assumed filament actions would be rejected if the printer wasn't paused, in an error state or had just been unlocked and wasnt expecting it to interrupt the print to do so. It was stupid but might be a valid edge case not envisioned....it might also be operating as intended ;-). If so, please close the issue.

HH v1.2.3-11-g4d3383f 
Klipper v0.11.0-86-g6026a99a

ningj#6911

**Comment by moggieuk** [comment]
Hi Nigel, thanks for the note.  Yes it could be more robust.  There are some things that are ok to do when printing (TTG map, changing config, etc) but the one that break the print like eject, gate change could be prevented...

**Comment by moggieuk** [comment]
I'm going to close this as "not planned" because although good in concept, it's not possible to implement.
