### ISSUE TITLE
typo error

### ISSUE THREAD

**Issue by Benoitone** [moggieuk/ERCF-Software-V3#42]
https://github.com/moggieuk/ERCF-Software-V3/blame/8b8a6ae63b8284804d3fccb8d01e7360dd12efa3/doc/DIFFERENCES.md?plain=1#L12

`ERCF_CHANGE_TOOL STNDALONE=1 TOOL={initial_tool}`
must be change to:
`ERCF_CHANGE_TOOL STANDALONE=1 TOOL={initial_tool}`

**Comment by moggieuk** [comment]
Fixed and pushed. Thank you.
