### ISSUE TITLE
"Extruder not configured" with "M104 T1 S200"

### ISSUE THREAD

**Issue by Tathar** [moggieuk/ERCF-Software-V3#56]
when commissioning my ERCF, I have an error "Extruder not configured" with the command "M104 T1 S0" generated by cura

**Comment by favoritewky** [comment]
You need change the single extruder with multicolor checkbox. Something like that.

**Comment by Tathar** [comment]
THANKS,
I solved the problem by creating the macro

`
[gcode_macro M104]
rename_existing: M104.1
gcode:
    {% set TOOL = params.T|default(0)|int %}
    {% set TEMP = params.S|default(0)|float %}

    M104.1 T0 S{TEMP}
`
