### ISSUE TITLE
KlipperScreen does not show current Gate Map

### ISSUE THREAD

**Issue by fabiandj64** [moggieuk/ERCF-Software-V3#58]
When i edited the Gates via KlipperScreen, the Values will be saved in ercf_vars.cfg. But when i restart KlipperScreen or Firmware or whole printer, everything on KlipperScreen is back to default. ercf_vars.cfg still shows the edited Values.

**Comment by moggieuk** [comment]
What is your `persistence_level` defined in ercf_parameters.cfg?   If not a high enough value,  changes will not be reloaded on reboot/restart.  This is as designed.  Read the comments in ercf_parameters.cfg...  setting to a level of `4' will restart with ALL state including selector position for example.

**Comment by fabiandj64** [comment]
guess i overlooked that option *facepalm*

closed
