### ISSUE TITLE
Moonraker.conf Creates INVALID

### ISSUE THREAD

**Issue by AustinTylerDean** [moggieuk/ERCF-Software-V3#82]
Hi There! I'm trying to figure out why my installation is not finding the git version, which is what I assume the problem is.

![image](https://github.com/moggieuk/ERCF-Software-V3/assets/38908303/3fb9e308-ab93-4ba1-810a-c503b03bba81)

![image](https://github.com/moggieuk/ERCF-Software-V3/assets/38908303/81627db8-742b-43b0-bba3-d0fed7856e93)

I've copied and pasted the update_manager portion, and I have 6 other managers working fine, so connection doesn't seem to be the issue. Is there something specific you have to do in github to allow calls for the current version number?

My home directory is correct...
![image](https://github.com/moggieuk/ERCF-Software-V3/assets/38908303/c49dd176-54ae-45ae-ac6f-8da9482f3cf7)

Any ideas?

**Comment by AustinTylerDean** [comment]
![image](https://github.com/moggieuk/ERCF-Software-V3/assets/38908303/4d03ca9f-b288-4cfe-b235-18ac434be3d5)

Like I said, I thought my home directory was okay...

**Comment by Surion79** [comment]
`pi` please. ;)

**Comment by AustinTylerDean** [comment]
What does my username have to do with it?

**Comment by kolbenhans** [comment]
your klipper, moonraker etc are also stored under this user & home directory, in that case it should working correct i guess.

**Comment by AustinTylerDean** [comment]
The answer is that ~/ERCF-Software-V3 was owned by root, not the user. Solution was to putty into ~ and run "sudo chown -R <username> ~/ERCF-Software-V3"

The -R is important, as without it you end up owning a directory but none of the contents... Good ol' Linux.
